<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Sandy" failures="2" tests="2" name="Add Customer Test" time="0.64" errors="0" timestamp="28 Feb 2022 09:17:15 GMT">
  <testcase classname="com.w2a.testcases.AddCustomerTest" name="addCustomer" time="0.334">
    <failure type="java.lang.AssertionError" message="Customer not added successfully">
      <![CDATA[java.lang.AssertionError: Customer not added successfully
at com.w2a.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:33)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- addCustomer -->
  <testcase classname="com.w2a.testcases.AddCustomerTest" name="addCustomer" time="0.289">
    <failure type="java.lang.AssertionError" message="Customer not added successfully">
      <![CDATA[java.lang.AssertionError: Customer not added successfully
at com.w2a.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:33)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- addCustomer -->
</testsuite> <!-- Add Customer Test -->
